use client
import './globals.css'
import { useEffect } from 'react'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Worqhat-TxtToCode',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
    const loadInter = async () => {
      const inter = await Inter({ subsets: ['latin'] })
      document.body.classList.add(inter.className)
    }

    loadInter()
  }, [])

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
